In [1]:
pip install yfinance

Requirement already satisfied: yfinance in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (1.3.0)
Requirement already satisfied: pandas>=1.3.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (2.2.6)
Requirement already satisfied: requests>=2.31 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (4.9.1)
Requirement already satisfied: pytz>=2022.5 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.1.4)
Requirement already satisfied: rich in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.22)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from requests>=2.31->yfinance) (2.6.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\marco\miniconda3\envs\pydata-book\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import yfinance as yf 
import numpy as np
import pandas as pd

tickers = ["AAPL", "MSFT"] # descarga de precios historicos de las acciones.

data = yf.download(tickers, start="2020-01-01", end="2024-01-01")
print(data.columns) # lo ideal es revisar primero el nombre de las columnas.

[*********************100%***********************]  2 of 2 completed

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'MSFT'),
            (  'High', 'AAPL'),
            (  'High', 'MSFT'),
            (   'Low', 'AAPL'),
            (   'Low', 'MSFT'),
            (  'Open', 'AAPL'),
            (  'Open', 'MSFT'),
            ('Volume', 'AAPL'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])

In [9]:
#adj close es el precio real de la acción, es el dato más puro en finanzas porque elimina el "ruido" que generan los eventos corporativos.
# Mientras que el Close (Precio de Cierre) es simplemente el precio al que terminó la acción en el mercado, 
# el Adj Close recalcula ese precio hacia atrás para reflejar el valor económico real que recibió el inversor
# Cuando una empresa reparte dinero a sus accionistas, ese efectivo sale de la valoración de la empresa. en algunos casos Adj Close no existe,
#entonces se trabaja con Close
precios = data["Close"]

In [10]:
precios

Ticker            AAPL        MSFT
Date
2020-01-02   72.400513  152.158417
2020-01-03   71.696625  150.263794
2020-01-06   72.267937  150.652161
2020-01-07   71.928040  149.278564
2020-01-08   73.085114  151.656311
...                ...         ...
2023-12-22  191.609451  368.236603
2023-12-26  191.065125  368.315308
2023-12-27  191.164093  367.735260
2023-12-28  191.589661  368.924805
2023-12-29  190.550461  369.671936

[1006 rows x 2 columns]

In [11]:
# Los precios solos no sirven de nada, ahora se van a transformar en rendimientos y se calculará el rendimiento porcentual diario
rendimientos = precios.pct_change()

In [12]:
rendimientos # en  este caso es completamente normal que el primer dato tenga NaN, ya que no hay día anterior.

Ticker          AAPL      MSFT
Date
2020-01-02       NaN       NaN
2020-01-03 -0.009722 -0.012452
2020-01-06  0.007968  0.002585
2020-01-07 -0.004703 -0.009118
2020-01-08  0.016087  0.015928
...              ...       ...
2023-12-22 -0.005548  0.002784
2023-12-26 -0.002841  0.000214
2023-12-27  0.000518 -0.001575
2023-12-28  0.002226  0.003235
2023-12-29 -0.005424  0.002025

[1006 rows x 2 columns]

In [13]:
rendimientos.head()

Ticker          AAPL      MSFT
Date
2020-01-02       NaN       NaN
2020-01-03 -0.009722 -0.012452
2020-01-06  0.007968  0.002585
2020-01-07 -0.004703 -0.009118
2020-01-08  0.016087  0.015928

In [14]:
# para eliminar campos NaN
rendimientos = rendimientos.dropna()

In [16]:
rendimientos.head()

Ticker          AAPL      MSFT
Date
2020-01-03 -0.009722 -0.012452
2020-01-06  0.007968  0.002585
2020-01-07 -0.004703 -0.009118
2020-01-08  0.016087  0.015928
2020-01-09  0.021241  0.012493

In [18]:
rendimientos.shape # shape indica las dimensiones

(1005, 2)

In [30]:
rendimientos.mean() # rendimiento promedio diario (esperado) y es el retorno aritmético real

Ticker
AAPL    0.001187
MSFT    0.001095
dtype: float64

In [22]:
rendimientos.std() # mide la volatilidad de las acciones.

Ticker
AAPL    0.021146
MSFT    0.020546
dtype: float64

In [23]:
rendimientos.corr()

Ticker      AAPL      MSFT
Ticker
AAPL    1.000000  0.777003
MSFT    0.777003  1.000000

In [24]:
# Correlación = 0.777, esto indica que se mueven bastante parecido, pero no idéntico 
# +1 → se mueven exactamente igual
# 0 → independientes
# -1 → se mueven en sentido opuesto
# la diversificación es limitada cuando la correlación es alta

In [25]:
#Aunque Apple y Microsoft presentan retornos y volatilidades similares, la alta correlación entre ambos activos (0.77) indica que se 
#comportan de manera muy similar en el mercado. Esto limita significativamente los beneficios de diversificación, por lo que 
#un portafolio compuesto únicamente por estos activos no lograría una reducción sustancial del riesgo.

In [27]:
pesos = np.array([0.5, 0.5]) # aquí se define cuanto dinero se pone a cada acción
portafolio = rendimientos.values @ pesos

np.std(portafolio) # volatilidad del portafolio

np.float64(0.019639856578091804)

In [28]:
# La volatilidad del portafolio se reduce ligeramente debido a la diversificación, 
# sin embargo, la alta correlación entre los activos limita significativamente la magnitud de esta reducción.

In [29]:
#El portafolio construido con Apple y Microsoft presenta una ligera reducción en la volatilidad frente a los activos individuales. 
#Sin embargo, debido a la alta correlación entre ambos, los beneficios de diversificación son limitados, lo que sugiere la necesidad 
#de incluir activos con menor correlación para mejorar el perfil de riesgo.